name: expedicion_ambiental
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^17.3.0
  google_fonts: ^8.1.0
  flutter_animate: ^4.5.2
  uuid: ^4.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Versiones ajustadas para compatibilidad con Dart SDK 3.10.x
  build_runner: ^2.4.6
  hive_generator: ^1.1.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Rutas de assets del proyecto mapeadas correctamente por carpetas
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/ui/
    - assets/images/clasificaton/
    - assets/images/clasificaton/bins/
    - assets/images/clasificaton/covers/
    - assets/images/clasificaton/cards/level1/
    - assets/images/clasificaton/cards/level2/
    - assets/images/clasificaton/waste/
